In [ ]:
#Task 1
import numpy as np
# Question 1
array_empty_2d = np.empty([2,2])
print(array_empty_2d)
# Question 2
array_onearray = np.ones([4,2])
print(array_onearray)
#Question 3
array_full = np.full([3,3],6)
print(array_full)
#Question 4
array_zeros = np.zeros_like(array_full)
print(array_zeros)
#Question 5
array_ones = np.ones_like(array_full)
print(array_ones)
#Question 6
new_list = [1,2,3,4]
new_array = np.array(new_list)
print(new_array)





[[4.94742041e-310 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000]]
[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]
[[6 6 6]
 [6 6 6]
 [6 6 6]]
[[0 0 0]
 [0 0 0]
 [0 0 0]]
[[1 1 1]
 [1 1 1]
 [1 1 1]]
[1 2 3 4]


In [ ]:
#Task 2
import numpy as np
#Question 1
array_numbers = np.arange(10,50)
print(array_numbers)
#Question 2
array_3d = np.arange(27).reshape(3,3,3)
print(array_3d)
#Question 3
array_3d_identity = np.eye(3)
print(array_3d_identity)
#Question 4
random_array = np.random.random()
mean = np.mean(random_array)
print(mean)
#Question 5
random_array_10d = np.random.rand(10,20)
min_value = np.min(random_array_10d)
max_value = np.max(random_array_10d)
print(min_value)
print(max_value)
#Question 6
zero_arrays = np.zeros(10)
zero_arrays[4] = 1
print(zero_arrays)
#Question 7
arr = [1,2,0,0,4,0]
reverse_array = np.flip(arr)
print(reverse_array)
#Question 8
new_array = np.zeros((4,4))
arranged_array = np.pad(new_array, pad_width=1,mode='constant',constant_values=1)
print(arranged_array)
#Question 9
checkerboard = np.zeros((8,8))
checkerboard[1::2,::2] = 1
checkerboard[::2,1::2] = 1
print(checkerboard)




[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]
[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
0.9679459481869698
0.005780948774267269
0.9961229567118466
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
[0 4 0 0 2 1]
[[1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1.]]
[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


In [ ]:
#Task 3
x = np.array([[1,2],[3,5]])
y = np.array([[5,6],[7,8]])
v = np.array([9,10])
w = np.array([11,12])
#Question 1
add = np.add(x,y)
print("addition",add)
#Question 2
sub = np.subtract(x,y)
print("subtraction",sub)
#Question 3
mul = np.multiply(v,w)
print("multiplication",mul)
#Question 4
square = np.square(x)
print("square",square)
#Question 5
dot_product1 = np.dot(v,w)
dot_product2 = np.dot(x,v)
dot_product3 = np.dot(x,y)
print("Dot product1: ",dot_product1)
print("Dot product2: ",dot_product2)
print("Dot product3: ",dot_product3)
#Question 6
concatenate = np.concatenate((x,y),axis= 0)
print("Concatenate: ",concatenate)
#Question 7
concatenate2 = np.concatenate((v,w),axis=1)
print("Concatenate: ",concatenate2)
#Because Dimension is different




addition [[ 6  8]
 [10 13]]
subtraction [[-4 -4]
 [-4 -3]]
multiplication [ 99 120]
square [[ 1  4]
 [ 9 25]]
Dot product1:  219
Dot product2:  [29 77]
Dot product3:  [[19 22]
 [50 58]]
Concatenate:  [[1 2]
 [3 5]
 [5 6]
 [7 8]]


AxisError: axis 1 is out of bounds for array of dimension 1

In [ ]:
#Task 4
A = np.array([[3,4],[7,8]])
B = np.array([[5,3],[2,1]])
#Question 1
A_inv = np.linalg.inv(A)
print("Inverse of A: ",A_inv)
A_pro = np.dot(A,A_inv)
A_result = np.round(A_pro)
print("Result of A: ",A_result)
#Question 2
AB_ind_pro = np.dot(A,B)
AB_result = np.round(AB_ind_pro)
print("Result of AB: ",AB_result)
BA_ind_pro = np.dot(B,A)
BA_result = np.round(BA_ind_pro)
print("Result of AB: ",BA_result)
#Question 3
AB_transpose = np.transpose(AB_ind_pro)
print("Transpose of AB: ",AB_transpose)
A_transpose = np.transpose(A)
B_transpose = np.transpose(B)
AB_transpose_pro = np.dot(A_transpose,B_transpose)
AB_transpose_result = np.round(AB_transpose_pro)
print("Result of AB transpose: ",AB_transpose_result)
#Question 4
array_1=np.array([[2,-3,1],[1,-1,2],[3,1,-1]])
array_2 = np.array([-1,-3,9])
array1_inv = np.linalg.inv(array_1)
X = np.dot(array1_inv,array_2 )
print(X)




Inverse of A:  [[-2.    1.  ]
 [ 1.75 -0.75]]
Result of A:  [[1. 0.]
 [0. 1.]]
Result of AB:  [[23 13]
 [51 29]]
Result of AB:  [[36 44]
 [13 16]]
Transpose of AB:  [[23 51]
 [13 29]]
Result of AB transpose:  [[36 13]
 [44 16]]
[ 2.  1. -2.]
